### ISSUE TITLE
add_underglow not working on errorbars

### ISSUE THREAD

**Issue by davidjwilson** [dhaitz/mplcyberpunk#11]
Hi, just started getting this error when trying to add underglow to an errorbar. Was working fine a few weeks ago.

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Full output:
![image](https://user-images.githubusercontent.com/16992317/149234143-afc450f5-20ca-4628-b3b7-5f660e06da1b.png)

**Comment by dhaitz** [comment]
Hi @davidjwilson , I can't reproduce this error. Which versions of Python / numpy / matplotlib / mplcyberpunk are you using?

**Comment by dhaitz** [comment]
closed because of inactivity
