### ISSUE TITLE
Option for changing colors

### ISSUE THREAD

**Issue by IshanJ25** [dhaitz/mplcyberpunk#19]
Could this feature please be added?

Custom colors for plot and custom gradient colors for graph area

Thankyou

**Comment by IshanJ25** [comment]
What I mean to say Is that I want to have this sort of plot using your theme:
![image](https://user-images.githubusercontent.com/86649457/180263601-355d753a-b4bb-4aba-9e1a-dbad69948853.png)

How can I possibly achieve this setting?

**Comment by dhaitz** [comment]
as a workaround, can you try plotting the positive and negative parts separately with different colors?

**Comment by IshanJ25** [comment]
However what i wanted has been achieved, I shared this code so that it could be incorporated in this repository.

Please add me as a contributor if you decide to add this feature, thanks.

**Comment by mayurankv** [comment]
I would also love this feature! If this was added to the repository, that would be great in my opinion!
