### ISSUE TITLE
Glow effect may mutate tick labels

### ISSUE THREAD

**Issue by jgehrcke** [dhaitz/mplcyberpunk#2]
Without calling `mplcyberpunk.add_glow_effects()`:

![Screenshot from 2020-03-30 20-17-36](https://user-images.githubusercontent.com/265630/77947093-ad4e4b00-72c3-11ea-98ae-b34f677b5d5b.png)

With calling `mplcyberpunk.add_glow_effects()`:

![Screenshot from 2020-03-30 20-17-58](https://user-images.githubusercontent.com/265630/77947111-b4755900-72c3-11ea-81c3-264a819694f7.png)

The tick label text changed unexpectedly. Let me know if you need more detail w.r.t. context.

**Comment by jgehrcke** [comment]
Will try to use that in https://github.com/jgehrcke/covid-19-germany-gae once this is sorted out :).

**Comment by dhaitz** [comment]
Hi @jgehrcke , interesting find! The tick labels aren't explicitly modified, so I guess the additional mpl objects somehow impact the tick label formatting. Which Matplotlib version are you using? Could you try the individual `make_lines_glow()` and `add_underglow()` functions and provide more code context and a data sample?

**Comment by above-c-level** [comment]
Hey there @dhaitz! This isn't strictly related to the issue posted by @jgehrcke, but it could _possibly_ be stemming from the same issue. I went about trying to recreate the posted issue using Matplotlib version 3.2.1, and found that the `add_underglow()` method call does definitely change the bounds at least for the y axis. Here's a screenshot of the plot I get from only calling `make_lines_glow()` 
![image](https://user-images.githubusercontent.com/33842389/78468212-cf383b00-76d2-11ea-8e3c-5121ab417680.png)
and here's a screenshot of the plot from only calling `add_underglow()`
![image](https://user-images.githubusercontent.com/33842389/78468222-e545fb80-76d2-11ea-9575-10a09662e02d.png)

The code I'm using to get this is
```
import pandas as pd
import datetime
import matplotlib.pyplot as plt
import mplcyberpunk

from pandas.plotting import register_matplotlib_converters
from pandas_datareader.data import DataReader

start = datetime.datetime(2008, 1, 1)
end = datetime.datetime(2009, 6, 1)
apple = DataReader("AAPL", "yahoo", start, end)
coca_cola = DataReader("KO", "yahoo", start, end)

register_matplotlib_converters()
plt.style.use("cyberpunk")
plt.rcParams['figure.figsize'] = [20, 10]
plt.plot(apple.index, apple['Adj Close'], label="Apple")
plt.plot(coca_cola.index, coca_cola['Adj Close'], label="Google")
plt.legend()

# mplcyberpunk.add_glow_effects()
# mplcyberpunk.make_lines_glow()
mplcyberpunk.add_underglow()

plt.show()
```

It may also be worth noting that by re-limiting and autoscaling around the data restores the original plot (for me at least), so simply adding
```
axis = plt.gca()
axis.relim()
axis.autoscale()
```
before `plt.show()` works as a solution (albeit a less desirable one). I haven't looked through your codebase, but it may be worth just grabbing the x and y limits before applying the visual changes, and then re-applying them afterwards.

**Comment by dhaitz** [comment]
Hi @above-c-level , thanks for your feedback! I fixed the y-limits problem the way you suggested, see https://github.com/dhaitz/mplcyberpunk/commit/3fe31e570d5a6bb95923b6d9439d89f20934f1de

**Comment by above-c-level** [comment]
@dhaitz I've already upgraded from Pypi and everything seems to work fine for me! Hopefully that also fixes the issue @jgehrcke was having earlier. Cheers!

**Comment by dhaitz** [comment]
Closed due to inactivity
