### ISSUE TITLE
how to turn on the grid?

### ISSUE THREAD

**Issue by LukaPitamic** [dhaitz/mplcyberpunk#24]
First and foremost - AWESOME project.   
Working in data-analysis world I'm always missing some aesthetics to spice up the work. 

However I'm trying to get closer to examples displayed on _readme.md_ and I can't find any elegant way to show the grid. I can add it manually of course but the examples are so well balanced I wish I could achieve the same. Also what size and DPI were used for achieving this beauty?  
And again, thank you for taking care of something missing in this world ;).

**Comment by dhaitz** [comment]
Hi @LukaPitamic, thanks for the kind words! As mplcyberpunk is only a decorative layer, you can refer to the matplotlib docs for most options. See e.g. [here](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.grid.html) for grid options. Does this answer your question?

**Comment by LukaPitamic** [comment]
Hi @dhaitz,
thank you quick response. I'm aware of the _matplotlib_ grid options, I already started to "reverse engineer" the look from examples. I'm kind of struggling to get the same look though. If you don't mind sharing the exact _matplotlib_ object buildup (with all settings/parameters) - it would be super appreciated. But if you don't have it handy, please don't bother, I'll do my homework.
In any case, great work!

**Comment by dhaitz** [comment]
hi @LukaPitamic, which specific example from the README are you referring to?

**Comment by LukaPitamic** [comment]
...any example with visible grid would do, but if I have to pick one, then:
 
![colormap](https://user-images.githubusercontent.com/34914144/211195090-4ec5ea15-9285-4a96-b42a-078f5b948d1d.png)

I'm after the visual balance between grid and axis. It's a combination of plot size (and DPI setting) and grid & axis lines width.
Thanks!

**Comment by dhaitz** [comment]
Here you go:

```python
import numpy as np
import matplotlib.pyplot as plt
import mplcyberpunk

plt.style.use("cyberpunk")
plt.rcParams['figure.dpi'] = 100

x = np.linspace(0, 2*np.pi, 128)

n = 20
colors = plt.cm.cool(np.linspace(0,1,n))

for i in range(n): 
    y = np.cos(x) * (i-(n-1)/2)
    plt.plot(x, y, color=colors[i])

mplcyberpunk.make_lines_glow()
plt.show()
```

Please let me know if this is sufficient.

**Comment by LukaPitamic** [comment]
**AMAZING!!!**

@dhaitz, thank you very, very much.
From now on the world observed through data also looks great!
