### ISSUE TITLE
Add colormaps

### ISSUE THREAD

**Issue by laserkelvin** [dhaitz/mplcyberpunk#3]
Absolutely loving this stylesheet!

One thing I've found that I wanted to do was use some of the cyberpunk colors as linear colormaps, and basically implement some functions that return `LinearSegmentedColormap` objects for others to use (example attached), in the same kind of way as how [palettable](https://jiffyclub.github.io/palettable/) gives access to a bunch of colormaps.

![c_ramp](https://user-images.githubusercontent.com/17684745/78257941-87de5e80-74c8-11ea-893f-e97e1327fbc4.png)

In this example I'm using cyan to violet (which actually makes a good sequential colormap), but some of the others like `pink` and `matrix_green` in the stylesheet looks like they'd be good candidates too. To make the plot above, I took the hex codes and converted them into normalized RGB values, and used `matplotlib.colors.LinearSegementedColormap.from_list` to create them. 

If you are open to contributions, I could fork/implement this and submit a PR :)

**Comment by dhaitz** [comment]
Hi @laserkelvin ,

thanks for your feedback and the suggestion!! I guess using one of matplotlib's built-in colormaps would be a simple solution, e.g. `cool`:

![image](https://user-images.githubusercontent.com/5802753/78286625-3e6e2d80-7521-11ea-978a-96ec42f5d6ca.png)

The colors used in the high-lightness colormaps in the Sequential2 section (`winter`, `autumn`, `spring`, `cool`, ...) seem pretty similar to the default colors in this package
