### ISSUE TITLE
grid toggle side effect

### ISSUE THREAD

**Issue by BMaxV** [dhaitz/mplcyberpunk#4]
Using the theme toggles the grid, not really a bug, but something users should be aware of when putting in those lines to make the effects work.

Put differently, I used the style and wondered where my grid had gone.

**Comment by dhaitz** [comment]
Hi @BMaxV , interesting side effect! Did you call plt.grid(), before or after setting the style? Could you provide a minimum code example for reproducibility?

**Comment by BMaxV** [comment]
Sure, no problem:

```
import matplotlib.pyplot as plt
import mplcyberpunk

def test():
    plt.style.use("cyberpunk")
    
    plt.plot([0,1,5,10],[1,2,1,2])
    plt.grid() # this line
    
    plt.show()

if __name__=="__main__":
    test()
```
