### ISSUE TITLE
Support Step plots

### ISSUE THREAD

**Issue by diceroll123** [dhaitz/mplcyberpunk#7]
Step plots would be nice to have working with underglow.

![image](https://user-images.githubusercontent.com/1243957/129652429-37138289-7005-42cf-a71e-9facd2be83c9.png)

I may get around to making a PR for this when I'm free to do so, but I don't know when I'd get around to it. In any case, or if anyone else were up for it, for now I'll make this issue.

**Comment by dhaitz** [comment]
Hi @diceroll123! #8 by @Mitch-ml addresses  this issue. Step plot functionality is now included in mplcyberpunk 0.3.0. Could you check? thanks!

**Comment by diceroll123** [comment]
Works perfectly! Great work @Mitch-ml.

Closing!
